### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mwaskom** [AnneCollins/TenSimpleRulesModeling#1]
Thanks for making these helpful examples public! I liked the paper too.

I was thinking about translating some of the examples to Python, for my own benefit and in case others would be interested. Before I could do that though, the code would need to be made available under an open source license (technically, code that is posted online without one is not actually "open-source").

There are many different kind of open-source licenses with [slightly different implications](https://choosealicense.com/) for what people can do with the code.  My suggestion would be the [MIT license](https://choosealicense.com/licenses/mit/). If you agree, I can also open a pull request to add it, to make things easy.

**Comment by AnneCollins** [comment]
Hi Michael,
Thanks for the feedback. I'm fairly new to code sharing, so your comments
are helpful! Sure, I'm happy to change the license, it would be great to
have python examples too.
Anne


Le dim. 14 avr. 2019 à 12:44, Michael Waskom <notifications@github.com> a
écrit :

**Comment by mwaskom** [comment]
Great! I did it in #2
